### ISSUE TITLE
Module not registered

### ISSUE THREAD

**Issue by lapo-luchini** [caddy-dns/acmeproxy#2]
I tried a `caddy upgrade` and I got this:

`Error: download failed: download failed: HTTP 400: github.com/caddy-dns/acmeproxy is not a registered Caddy module package path (id=f357f6f2-90ef-4c80-985c-9a126ee62bf4)`

I know little about this but I guess this is the same as caddy-dns/googleclouddns#3?

**Comment by KalleDK** [comment]
@mholt - you maybe know more about this?

**Comment by mholt** [comment]
Ah, it just needs to be registered on our website: https://caddyserver.com -- click Account, then login (or create an account), then claim your package: `github.com/caddy-dns/acmeproxy`

**Comment by KalleDK** [comment]
> Ah, it just needs to be registered on our website: https://caddyserver.com -- click Account, then login (or create an account), then claim your package: `github.com/caddy-dns/acmeproxy`

Done. Hope that help @lapo-luchini

**Comment by lapo-luchini** [comment]
Works perfectly, thanks!
